"""add user bio

Revision ID: 13690d1e4995
Revises: 4c2f6a1b8d90
Create Date: 2026-01-20 07:10:29.018800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13690d1e4995"
down_revision: Union[str, None] = "4c2f6a1b8d90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("media_object_key_key", "media", type_="unique")
    op.drop_index("ix_media_object_key", table_name="media")
    op.create_index(op.f("ix_media_object_key"), "media", ["object_key"], unique=True)
    op.add_column("users", sa.Column("bio", sa.String(length=100), nullable=True))
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.drop_index("ix_users_email", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index("ix_users_username", table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_column("users", "bio")
    op.drop_index(op.f("ix_media_object_key"), table_name="media")
    op.create_index("ix_media_object_key", "media", ["object_key"], unique=False)
    op.create_unique_constraint("media_object_key_key", "media", ["object_key"])
    # ### end Alembic commands ###
