"""add media table

Revision ID: 3f7f8a5cfc0f
Revises: 1b2c3d4e5f6a
Create Date: 2026-01-18 06:47:47.881465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f7f8a5cfc0f"
down_revision: Union[str, None] = "1b2c3d4e5f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("public_url", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(op.f("ix_media_id"), "media", ["id"], unique=False)
    op.create_index(op.f("ix_media_object_key"), "media", ["object_key"], unique=False)
    op.add_column("posts", sa.Column("media_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_posts_media_id", "posts", "media", ["media_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("users", sa.Column("avatar_media_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_users_avatar_media_id",
        "users",
        "media",
        ["avatar_media_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_avatar_media_id", "users", type_="foreignkey")
    op.drop_column("users", "avatar_media_id")
    op.drop_constraint("fk_posts_media_id", "posts", type_="foreignkey")
    op.drop_column("posts", "media_id")
    op.drop_index(op.f("ix_media_object_key"), table_name="media")
    op.drop_index(op.f("ix_media_id"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
