"""add comments

Revision ID: b8d7aa85617e
Revises: cff762dd372b
Create Date: 2026-02-05 08:23:55.292621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d7aa85617e'
down_revision: Union[str, None] = 'cff762dd372b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_comment_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=400), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_comment_id'], ['comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_parent_sort', 'comments', ['parent_id', 'like_count', 'created_at', 'id'], unique=False)
    op.create_index('ix_comments_post_parent_sort', 'comments', ['post_id', 'parent_id', 'like_count', 'created_at', 'id'], unique=False)
    op.create_index('ix_comments_reply_to_comment', 'comments', ['reply_to_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_reply_to_user_id'), 'comments', ['reply_to_user_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_reply_to_user_id'), table_name='comments')
    op.drop_index('ix_comments_reply_to_comment', table_name='comments')
    op.drop_index('ix_comments_post_parent_sort', table_name='comments')
    op.drop_index('ix_comments_parent_sort', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
